from temperature_detection.process.models.double_conv import DoubleConv
from temperature_detection.process.models.pre_trained_models.pre_trained import PreTrained
from temperature_detection.process.models.triple_conv import TripleConv
